function SpawnRegions()
	return {
		{ name = "Shelter 41 25", file = "media/maps/Shelter 41 25/spawnpoints.lua" },
		{ name = "Shelter 22 38", file = "media/maps/Shelter 22 38/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "EP MFD", file = "media/maps/EP MFD/spawnpoints.lua" },
		{ name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua" },
		{ name = "Crowlake", file = "media/maps/Crowlake/spawnpoints.lua" },
		{ name = "YakamaStatePark", file = "media/maps/YakamaStatePark/spawnpoints.lua" },
		{ name = "RailyardIndustry", file = "media/maps/RailyardIndustry/spawnpoints.lua" },
		{ name = "alshardware", file = "media/maps/alshardware/spawnpoints.lua" },
		{ name = "bonefield", file = "media/maps/bonefield/spawnpoints.lua" },
		{ name = "BuffaloHill", file = "media/maps/BuffaloHill/spawnpoints.lua" },
		{ name = "callcenter", file = "media/maps/callcenter/spawnpoints.lua" },
		{ name = "Constown", file = "media/maps/Constown/spawnpoints.lua" },
		{ name = "Kentucky Wilds", file = "media/maps/Kentucky Wilds/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Greenport", file = "media/maps/Greenport/spawnpoints.lua" },
		{ name = "GustonKY", file = "media/maps/GustonKY/spawnpoints.lua" },
		{ name = "Hartburg", file = "media/maps/Hartburg/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Fort_Boonesborough", file = "media/maps/Fort_Boonesborough/spawnpoints.lua" },
		{ name = "MREX", file = "media/maps/MREX/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "TrimbleCountyPowerStation", file = "media/maps/TrimbleCountyPowerStation/spawnpoints.lua" },
		{ name = "Hopewell, KY", file = "media/maps/Hopewell, KY/spawnpoints.lua" },
		{ name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua" },
		{ name = "Tandil", file = "media/maps/Tandil/spawnpoints.lua" },
		{ name = "Tikitown", file = "media/maps/Tikitown/spawnpoints.lua" },
		{ name = "riversidemansion", file = "media/maps/riversidemansion/spawnpoints.lua" },
		{ name = "Rosewood VHS Store", file = "media/maps/Rosewood VHS Store/spawnpoints.lua" },
		{ name = "PineVille", file = "media/maps/PineVille/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "lvharbor", file = "media/maps/lvharbor/spawnpoints.lua" },
		{ name = "Filtration Plant", file = "media/maps/Filtration Plant/spawnpoints.lua" },
		{ name = "Louisville_Riverboat", file = "media/maps/Louisville_Riverboat/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "lighthouse", file = "media/maps/lighthouse/spawnpoints.lua" },
		{ name = "LCV2", file = "media/maps/LCV2/spawnpoints.lua" },
		{ name = "lvinternationalairport", file = "media/maps/lvinternationalairport/spawnpoints.lua" },
		{ name = "Nettle Township", file = "media/maps/Nettle Township/spawnpoints.lua" },
		{ name = "NewEllroy", file = "media/maps/NewEllroy/spawnpoints.lua" },
		{ name = "OakDaleUniversity", file = "media/maps/OakDaleUniversity/spawnpoints.lua" },
		{ name = "McAlpine Locks and Dam", file = "media/maps/McAlpine Locks and Dam/spawnpoints.lua" },
		{ name = "12_27", file = "media/maps/12_27/spawnpoints.lua" },
		{ name = "OverlookHotel", file = "media/maps/OverlookHotel/spawnpoints.lua" },
		{ name = "elliotpondec", file = "media/maps/elliotpondec/spawnpoints.lua" },
		{ name = "Canvasback", file = "media/maps/Canvasback/spawnpoints.lua" },
		{ name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua" },
		{ name = "WestPointGatedCommunity", file = "media/maps/WestPointGatedCommunity/spawnpoints.lua" },
		{ name = "West Point Fire Department", file = "media/maps/West Point Fire Department/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
		{ name = "The Yacht", file = "media/maps/The Yacht/spawnpoints.lua" },
		{ name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua" },
		{ name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua" },
		{ name = "BBL", file = "media/maps/BBL/spawnpoints.lua" },
		{ name = "survivorwarehouse", file = "media/maps/survivorwarehouse/spawnpoints.lua" },
		{ name = "Shelter 22 28", file = "media/maps/Shelter 22 28/spawnpoints.lua" },
		{ name = "Shelter 25 33", file = "media/maps/Shelter 25 33/spawnpoints.lua" },
		{ name = "Shelter 29 26", file = "media/maps/Shelter 29 26/spawnpoints.lua" },
		{ name = "Shelter 40 30", file = "media/maps/Shelter 40 30/spawnpoints.lua" },
		{ name = "Shelter 45 15", file = "media/maps/Shelter 45 15/spawnpoints.lua" },
		{ name = "Shelter 49 12", file = "media/maps/Shelter 49 12/spawnpoints.lua" },
		{ name = "Tower 13 26", file = "media/maps/Tower 13 26/spawnpoints.lua" },
		{ name = "Tower 47 22", file = "media/maps/Tower 47 22/spawnpoints.lua" },
		{ name = "BuildItCell1", file = "media/maps/BuildItCell1/spawnpoints.lua" },
		{ name = "BuildItCell2", file = "media/maps/BuildItCell2/spawnpoints.lua" },
	}
end
